Csv import/dbcreation bug
Sascha-Gschwind/incubator-superset pull request #53
Opened 2019-12-03 10:12 UTC by sloypog

### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

2019-12-03 14:23 UTC, Sascha-Gschwind commented on superset/config.py
> +POSTGRES_USERNAME = "postgres"
Muss vom Environment geladen werden

2019-12-03 14:23 UTC, Sascha-Gschwind commented on superset/config.py
> +POSTGRES_PASSWORD = "postgres"
Muss vom Environment geladen werden

2019-12-03 14:24 UTC, Sascha-Gschwind commented on superset/views/csv_import.py
> +            # TODO if there is time look for a better method to do this, otherwise document it
Don't check in TODO's in master, create an issue and point to this line of code in the issue

2019-12-03 14:25 UTC, Sascha-Gschwind requested changes
Please fix the comments first

2019-12-04 08:08 UTC, Sascha-Gschwind reviewed
We should probably merge the branch csv-import into this after #59 is merged and reapply the changes there

2019-12-04 08:35 UTC, Sascha-Gschwind approved these changes

2019-12-04 16:36 UTC, michellekunz approved these changes

2019-12-04 16:36 UTC, merged