Geocoding/early exit
Sascha-Gschwind/incubator-superset pull request #77
Opened 2019-12-10 10:27 UTC by sloypog

### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

2019-12-10 10:35 UTC, michellekunz approved these changes

2019-12-11 08:20 UTC, Sascha-Gschwind requested changes

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        # TODO There is no data returned here
Should be solved in this PR? Please fix TODO's first

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        if data[0]:
Maybe add a comment here explaining why we check data[0]

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +            # TODO make this generic only for testing
Please fix TODO's

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +            if not data[0]:
I would check the length of data maybe? checking data[0] here is really confusing since we check it a few lines above to tell if it worked or not

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        # TODO change to more appropriate name
Fix TODO's

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        # TODO fix with schema
Fix TODO's

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +            # sql = "SELECT " + column_list + ' FROM %s' % table_name
Remove this column when it's not needed anymore

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        database = (
Does the table itself not contain a reference to the database?  Would make this call unnecessary, if not it's ok

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        # connection = database.db_engine_spec.connect()
Remove comment if it's not needed anymore

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        # connection = db.engine.connect()
Remove comment if it's not needed anymore

2019-12-11 08:20 UTC, Sascha-Gschwind commented on superset/views/geocoding.py
> +        # transaction = connection.begin()
Remove comment if it's not needed anymore

2019-12-11 09:47 UTC, Sascha-Gschwind approved these changes

2019-12-11 09:55 UTC, merged